from PyQt5.QtWidgets import *
#import character_gui
app = QApplication([])
button = QPushButton('Click')
button2 = QPushButton('Click2')

def on_button_clicked():
    alert = QMessageBox()
    alert.setText('You clicked the button!')
    layout.addWidget(QPushButton('Bottom2'))
    button3 = QPushButton('Click3')
    layout.addWidget(button3)
    alert.exec_()
window = QWidget()
layout = QVBoxLayout()
layout.addWidget(QPushButton('Top'))
layout.addWidget(QPushButton('Bottom'))
layout.addWidget(button)
layout.addWidget(button2)
window.setLayout(layout)
window.show()
button.clicked.connect(on_button_clicked)
button2.clicked.connect(on_button_clicked)
#button.show()
#button2.show()
app.exec_()
